name 'brew-mac'
maintainer 'Karthik Muthupalaniappan'
maintainer_email 'karthik.swaminathan@gmail.com'
license 'all_rights'
description 'Installs/Configures a bunch of stuff on a Mac based developer machine'
long_description 'Installs/Configures a bunch of stuff on a Mac based developer machine'
version '0.1.0'
