name 'brew-mac'
maintainer 'Karthik Muthupalaniappan'
maintainer_email 'c.karthik.muthupalaniappan@uptake.com'
license 'all_rights'
description 'Installs/Configures brew-mac'
long_description 'Installs/Configures brew-mac'
version '0.1.0'
